/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BucketListRouteImport } from './routes/bucket-list'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as LinksRouteImport } from './routes/links'
import { Route as UsesRouteImport } from './routes/uses'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BucketListRoute = BucketListRouteImport.update({
  id: '/bucket-list',
  path: '/bucket-list',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const UsesRoute = UsesRouteImport.update({
  id: '/uses',
  path: '/uses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bucket-list': typeof BucketListRoute
  '/guestbook': typeof GuestbookRoute
  '/links': typeof LinksRoute
  '/uses': typeof UsesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bucket-list': typeof BucketListRoute
  '/guestbook': typeof GuestbookRoute
  '/links': typeof LinksRoute
  '/uses': typeof UsesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bucket-list': typeof BucketListRoute
  '/guestbook': typeof GuestbookRoute
  '/links': typeof LinksRoute
  '/uses': typeof UsesRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/bucket-list' | '/guestbook' | '/links' | '/uses' | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bucket-list' | '/guestbook' | '/links' | '/uses' | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/bucket-list'
    | '/guestbook'
    | '/links'
    | '/uses'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BucketListRoute: typeof BucketListRoute
  GuestbookRoute: typeof GuestbookRoute
  LinksRoute: typeof LinksRoute
  UsesRoute: typeof UsesRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bucket-list': {
      id: '/bucket-list'
      path: '/bucket-list'
      fullPath: '/bucket-list'
      preLoaderRoute: typeof BucketListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uses': {
      id: '/uses'
      path: '/uses'
      fullPath: '/uses'
      preLoaderRoute: typeof UsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BucketListRoute: BucketListRoute,
  GuestbookRoute: GuestbookRoute,
  LinksRoute: LinksRoute,
  UsesRoute: UsesRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
